services:
  twitter-scraper:
    build: .
    env_file:
      - .env.local
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=twitter
      - TARGET_ACCOUNTS=elonmusk,NASA
      - KEYWORDS=mars,crypto
    depends_on:
      - postgres
    # Or specify individual environment variables:
    # environment:
    #   - TWITTER_USERNAME=${TWITTER_USERNAME}
    #   - TWITTER_PASSWORD=${TWITTER_PASSWORD}
    #   - TWITTER_EMAIL=${TWITTER_EMAIL}
    #   - TWITTER_COOKIES=${TWITTER_COOKIES}
    #   - PROXY_URL=${PROXY_URL}

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=twitter
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: